# Basic Site Settings
locale                   : "en-US"
title                    : "Fin Amin's Research Portfolio"
title_separator          : "-"
name                     : &name "Fin Amin"
description              : &description "PhD candidate in Electrical Engineering at NCSU, focusing on AI, RL in EDA, and neural network calibration."
url                      : "https://FinAmin.github.io"
baseurl                  : ""
repository               : "FinAmin/FinAmin.github.io"

# Author Details
author:
  avatar                 : "profile.png"
  name                   : "Fin Amin"
  bio                    : "Graduate Research Scientist at MIT Lincoln Laboratory and PhD Candidate at NCSU, specializing in AI, RL, and neural network calibration."
  location               : "Raleigh, NC"
  employer               : "MIT Lincoln Laboratory"
  uri                    : "https://FinAmin.github.io"
  email                  : "samin2@ncsu.edu"
  
  # Academic and Social Links
  googlescholar          : "https://scholar.google.com/citations?user=yJv_j1AAAAAJ&hl=en"
  github                 : "FinAminToastCrunch"
  linkedin               : "your-linkedin-username"  # Update this with your actual LinkedIn username if you want it linked

# SEO Related (if you have these verifications, you can fill them in)
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics (if you use Google Analytics, enter your tracking ID here)
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-XXXXXXXXX-X"

# Plugins (if you use additional plugins, list them here)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
